import ApolloCookieWrapper from '#/components/ApolooCookieWrapper'
import { ConfirmContextProvider as ConfirmDialogContextProvider } from '#/context/ConfirmContextProvider'
import '#/styles/global.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode,
  params: {
    lng: string
  }
}) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <ApolloCookieWrapper>
          <ConfirmDialogContextProvider>
            {children}
          </ConfirmDialogContextProvider>
        </ApolloCookieWrapper>
      </body>
    </html>
  )
}
